### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by abdurahmanadilovic** [wardellbagby/WeightedShuffle#2]
I read the README file but I still did not understand the crux of the algorithm, how do you prevent two songs appearing back to back in a shuffle, do you make multiple passes and remove all same back to back songs?

**Comment by wardellbagby** [comment]
Firstly, I apologize; I didn't see this until now.

So, we don't really try super duper hard to have two songs not appear back to back. We do everything in a single-pass. The way it works it like this:

1. Give the shuffle a list of items. Let's say the items look like `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
2. Give the shuffle a way to group items. Let's say that grouping is `x%3`.
3. The shuffle will use the grouping to group all the items. That'll look like `[[1, 4, 7, 10], [2, 5, 8], [3, 6, 9]]`
4. The shuffle "equalize" all the groups. This just means that it'll insert fake items into every group so that they're all the same size. This will make it look like `[[1, 4, 7, 10], [2, 5, 8, -1], [3, 6, 9, -1]]` The `-1` are fake items and the shuffle is aware of them.
5. The shuffle shuffles all the groupings. This might look like `[[2, 5, 8, -1], [1, 4, 7, 10], [3, 6, 9, -1]]`
6. The shuffle iterates through all of the groups and chooses an item from each group it iterates over randomly. This might look like:

```
results = [5, 1]
items = `[[2, 8, -1], [4, 7, 10], [3, 6, 9]]`
```

Notice that the `[3, 6, 9]` no longer has a `-1` in it. The shuffle chose that, saw it was invalid, still removed it from the items list, but didn't add it to the results.

By following this, it greatly reduces the chances of selecting an item from the same group back to back, but it's still possible. This doesn't try to prevent that, just avoid it. 

Following this logic, if the groups were horribly uneven, something like `[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, -1, -1, -1, -1, -1, -1, -1, 1-, -1]]`, this is 100% going to fail. Even with something less uneven, sometimes it'll still fail because that's the randomness in it. I find that, in production, it's failure rate is acceptable, but my use case is purely for music shuffling so it failing isn't really an issue. 

I'll update the README sometime in the future that'll better explain this process. Feel free to respond if you have further questions.

**Comment by abdurahmanadilovic** [comment]
Ok, so in an essence you break songs into groups and you shuffle groups then you pick an item from a group randomly? The result is a list of items from each group, so in your example [5,1]. So after 5 and 1 are played the algorithm will keep taking songs until all groups are empty? Once the groups are empty the process repeats it self? Did you happen to measure the rate of collision (two songs appearing back to back) over time?

**Comment by wardellbagby** [comment]
In essence, yes. I don't measure the rate of collision in production, but there is a unit test that measures it with some hardcoded baselines so I can be somewhat confident in my changes.

**Comment by abdurahmanadilovic** [comment]
When you say production you mean some player you are using on your phone which implements this shuffle?

**Comment by wardellbagby** [comment]
Yes, that's correct.
